## 1. Primitives importantes de Numpy

1.1 Statisques de base

In [3]:
import numpy as np

data = np.array([1, 2, 3, 4])
mean_value = data.mean()
print("Moyenne :", mean_value)

Moyenne : 2.5


In [7]:
total = data.sum()
print("Somme :", total)

Somme : 10


In [9]:
variance = data.var()
print("Variance :", variance)

Variance : 1.25


1.2 Manipulation des tableaux

In [11]:
data = np.array([1, 2, 3, 4, 5, 6])
reshaped = data.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [13]:
data = np.array([[1,2],[3,4]])
print(data)
flattened = data.flatten()
print("===================\n",flattened)

[[1 2]
 [3 4]]
 [1 2 3 4]


In [14]:
transposed = data.transpose()
print(transposed)

[[1 3]
 [2 4]]


In [15]:
data1 = np.array([1,2])
data2 = np.array([3,4])
h_combined = np.hstack((data1, data2))
print("Horizontalement empilé :", h_combined)
v_combined = np.vstack((data1, data2))
print("Verticalement empilé :\n", v_combined)

Horizontalement empilé : [1 2 3 4]
Verticalement empilé :
 [[1 2]
 [3 4]]


In [16]:
data = np.array([10, 20, 30, 40,])
last_element = data[-1]
print("Dernier élément :", last_element)

Dernier élément : 40


In [18]:
data = np.array([10, 20, 30, 40, 50])
slice_data = data[::2]
print("Éléments aux indices pairs :", slice_data)

Éléments aux indices pairs : [10 30 50]


In [21]:
data = np.array([1, 2, 3, 4])
copied_data = data.copy()
copied_data[0] = 99
print("Original :", data)
print("Copié :", copied_data)

Original : [1 2 3 4]
Copié : [99  2  3  4]


1.3 Affichage des primier et dernier élements du dataset

In [24]:
dataset = np.arange(1, 101)
print("Premiers éléments :", dataset[:10])
print("Derniers éléments :", dataset[-10:])

Premiers éléments : [ 1  2  3  4  5  6  7  8  9 10]
Derniers éléments : [ 91  92  93  94  95  96  97  98  99 100]


1.5 Indexation avancée

In [27]:
# Fancy Indexing
data = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
selected = data[indices]
print(selected)

[10 30 50]


In [29]:
# masking
data = np.array([1, 2, 3, 4, 5])
filtered = data[data > 3]
print(filtered)

[4 5]


In [34]:
# where()
data = np.array([10, 20, 30, 40, 50])
condition = data > 30
resutl = np.where(condition)
print(resutl)

(array([3, 4]),)


In [35]:
import numpy as np
import pandas as pd
data = np.array([
    {"Nom": "Alice", "Classe": "Guerrier", "Niveau": 5},
    {"Nom": "Bob",  "Classe": "Mage", "Niveau": 3},
    {"Nom": "Charlie", "Classe": "Guerrier", "Niveau": 7},
])
data = np.array([
    ("Alice", "Guerrier", 5),
    ("Bob", "Mage", 3),
    ("Charlie", "Guerrier", 7)
], dtype=[('Nom','U10'), ('Classe','U10'), ('Niveau','i4')])

# Sélectionner tout les guerriers
guerriers = data[data["Classe"] == "Guerrier"]
print(guerriers)

[]


In [36]:
import numpy as np
import pandas as pd
data = np.array([
    {"Nom": "Alice", "Classe": "Guerrier", "Niveau": 5},
    {"Nom": "Bob",  "Classe": "Mage", "Niveau": 3},
    {"Nom": "Charlie", "Classe": "Guerrier", "Niveau": 7},
])
data = pd.DataFrame(data.tolist())
# Sélectionner tout les guerriers
guerriers = data[data["Classe"] == "Guerrier"]
print(guerriers)

       Nom    Classe  Niveau
0    Alice  Guerrier       5
2  Charlie  Guerrier       7


In [37]:
import numpy as np

# Création des tableaux
A = np.array([1, 2, 3])        # Shape: (3,)
B = np.array([[1], [2], [3]])  # Shape: (3, 1)

print("Tableau A:")
print(f"Shape: {A.shape}")
print(f"Valeurs: {A}")
print("\nTableau B:")
print(f"Shape: {B.shape}")
print(f"Valeurs:\n{B}")

# Opération avec broadcasting
result = A + B
print("\nRésultat A + B:")
print(f"Shape: {result.shape}")
print(f"Valeurs:\n{result}")

Tableau A:
Shape: (3,)
Valeurs: [1 2 3]

Tableau B:
Shape: (3, 1)
Valeurs:
[[1]
 [2]
 [3]]

Résultat A + B:
Shape: (3, 3)
Valeurs:
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
df = pd.read_csv("C:/Users/David BOHORQUEZ/Downloads/archive/dataset_joueurs.csv")

df.head()

,pseudo,nb_parties,nb_victoires,team,class
0,Player_1,71,5,Green,Guerrier
1,Player_2,34,27,Red,Archer
2,Player_3,91,14,Blue,Archer
3,Player_4,80,72,Red,Healer
4,Player_5,40,19,Green,Archer


TP : Comparaison entre np.sum et np.einsum sur un dataset NBA

In [19]:
pip install huggingface_hub datasets numba

   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   -------------------------------------- - 2.6/2.7 MB 21.3 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 11.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   ---- ----------------------------------- 4.7/38.1 MB 23.6 MB/s eta 0:00:02
   --------- ------------------------------ 9.4/38.1 MB 22.8 MB/s eta 0:00:02
   -------------- ------------------------- 14.2/38.1 MB 22.8 MB/s eta 0:00:02
   ------------------- -------------------- 18.9/38.1 MB 23.2 MB/s eta 0:00:01
   ------------------------- -------------- 24.1/38.1 MB 23.4 MB/s eta 0:00:01
   ----------------------------- ---------- 28.6/38.1 MB 23.1 MB/s eta 0:00:01
   ----------------------------------- ---- 33.8/38.1 MB 23.3 MB/s eta 0:00:01
   ---------------------------------------  38.0/38.1 MB 23.4 MB/s eta 0:00:01
   ---------------------------------------  38.0/38.1 MB 23.4 MB/s eta 0:00:0


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
import numpy as np
import pandas as pd

In [23]:
import pandas as pd

df = pd.read_csv("hf://datasets/yvonne90190/NBA_salary_advanced_stats/NBA_Data.csv")

arr = df.select_dtypes(include=['number'])

arr.head()

,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,3P%,FTM,...,FT%,REB,AST,STL,BLK,TO,DD2,TD3,year,salary
0,70,37.5,33.9,11.5,23.6,48.7,4.1,10.6,38.2,6.8,...,78.6,9.2,9.8,1.4,0.5,4.0,49,21,2023,40064220
1,73,35.2,30.4,11.5,18.8,61.1,0.5,1.7,27.4,7.0,...,65.7,11.5,6.5,1.2,1.1,3.4,57,10,2023,45640084
2,75,34.0,30.1,10.6,19.8,53.5,1.3,3.6,35.3,7.6,...,87.4,5.5,6.2,2.0,0.9,2.2,8,0,2023,33386850
3,77,35.4,28.7,10.3,21.4,47.9,2.7,6.8,40.1,5.5,...,84.7,3.6,6.7,0.9,0.2,2.4,9,0,2023,26346666
4,75,37.2,27.1,10.0,19.1,52.3,2.2,5.4,41.3,4.8,...,85.6,6.6,5.0,0.9,1.2,3.3,14,1,2023,47649433


In [24]:
import time

def calcul_numpy_standard(arr):
    """Version standard avec NumPy"""
    terme1 = np.sin(arr**2)
    terme2 = np.cos(2 * arr)
    terme3 = np.exp(-arr / 10)
    terme4 = np.log(np.abs(arr) + 1)
    terme5 = arr**2 + 1
    resultat = terme1 + terme2 * terme3 + terme4 / terme5
    return resultat

# Benchmark
def benchmark_standard():
    sizes = [10**5, 10**6, 10**7, 5*10**7]
    temps_standard = []
    for size in sizes:
        arr = np.random.randn(size)
        start = time.time()
        result = calcul_numpy_standard(arr)
        temps_exec = time.time() - start
        temps_standard.append(temps_exec)
        print(f"Taille {size}: {temps_exec:.4f} secondes")
    return temps_standard

In [25]:
import math
import time
import numpy as np
from numba import vectorize, float64

@vectorize([float64(float64)], nopython=True, target='parallel')
def ufunc_optimisee(x):
    """uFunc personnalisée optimisée"""
    x_carre = x * x
    sin_term = math.sin(x_carre)
    cos_term = math.cos(2 * x)
    exp_term = math.exp(-x / 10)
    log_term = math.log(abs(x) + 1)
    denom = x_carre + 1
    return sin_term + cos_term * exp_term + log_term / denom

def benchmark_ufunc():
    sizes = [10**5, 10**6, 10**7, 5*10**7]
    temps_ufunc = []
    for size in sizes:
        arr = np.random.randn(size)
        start = time.time()
        result = ufunc_optimisee(arr)
        temps_exec = time.time() - start
        temps_ufunc.append(temps_exec)
        print(f"Taille {size}: {temps_exec:.4f} secondes")
    return temps_ufunc

In [30]:
def benchmark_complet():
    sizes = [10**5, 10**6, 10**7]
    print("=== BENCHMARK NumPy vs uFuncs ===")
    print(f"{'Taille':<10} {'NumPy (s)':<12} {'uFunc (s)':<12} {'Speedup':<10}")
    print("-" * 50)
    for size in sizes:
        arr = np.random.randn(size)
        # Version NumPy standard
        start = time.time()
        result_std = calcul_numpy_standard(arr)
        time_std = time.time() - start
        # Version uFunc
        start = time.time()
        result_ufunc = ufunc_optimisee(arr)
        time_ufunc = time.time() - start
        # Vérification de l'exactitude
        diff_max = np.max(np.abs(result_std - result_ufunc))
        speedup = time_std / time_ufunc
        print(f"{size:<10} {time_std:<12.4f} {time_ufunc:<12.4f} {speedup:<10.2f}x")
        print(f"Erreur max: {diff_max:.2e}")
    return time_std, time_ufunc, speedup

print(benchmark_complet())

=== BENCHMARK NumPy vs uFuncs ===
Taille     NumPy (s)    uFunc (s)    Speedup   
--------------------------------------------------
100000     0.0097       0.0037       2.61      x
Erreur max: 0.00e+00
1000000    0.1147       0.0135       8.53      x
Erreur max: 0.00e+00
10000000   0.8862       0.1080       8.20      x
Erreur max: 0.00e+00
(0.8862245082855225, 0.1080315113067627, 8.20338897017768)


## MultiIndex

In [32]:
df = pd.read_csv("hf://datasets/yvonne90190/NBA_salary_advanced_stats/NBA_Data.csv")

df.head()

,player,team,POS,GP,MIN,PTS,FGM,FGA,FG%,3PM,...,FT%,REB,AST,STL,BLK,TO,DD2,TD3,year,salary
0,Luka Doncic,DAL,PG,70,37.5,33.9,11.5,23.6,48.7,4.1,...,78.6,9.2,9.8,1.4,0.5,4.0,49,21,2023,40064220
1,Giannis Antetokounmpo,MIL,PF,73,35.2,30.4,11.5,18.8,61.1,0.5,...,65.7,11.5,6.5,1.2,1.1,3.4,57,10,2023,45640084
2,Shai Gilgeous-Alexander,OKC,PG,75,34.0,30.1,10.6,19.8,53.5,1.3,...,87.4,5.5,6.2,2.0,0.9,2.2,8,0,2023,33386850
3,Jalen Brunson,NY,PG,77,35.4,28.7,10.3,21.4,47.9,2.7,...,84.7,3.6,6.7,0.9,0.2,2.4,9,0,2023,26346666
4,Kevin Durant,PHX,PF,75,37.2,27.1,10.0,19.1,52.3,2.2,...,85.6,6.6,5.0,0.9,1.2,3.3,14,1,2023,47649433


In [35]:
df_simple = df.groupby(['team', 'POS']).agg({
'PTS': 'mean',
'REB': 'mean',
'AST': 'mean'
}).reset_index()
print(df_simple.head())

  team POS        PTS       REB       AST
0  ATL   C   7.766667  5.649020  1.060784
1  ATL   F   7.496429  3.985714  1.075000
2  ATL   G   9.864103  2.569231  2.758974
3  ATL  PF   9.585000  5.076667  1.458333
4  ATL  PG  12.645161  2.251613  4.864516


In [36]:
df_complex = df.groupby(['team', 'POS', 'year']).agg({
'PTS': 'sum',
'REB': 'sum',
'AST': 'sum'
}).sort_index()
print(df_complex.head())

                PTS   REB  AST
team POS year                 
ATL  C   2001  23.2  16.5  1.3
         2002  14.3  13.2  1.6
         2003  11.3   5.6  0.9
         2004   5.7   2.6  0.3
         2005  13.5   9.1  1.8


## TP Python : Agrégation avancée avec Pandas

In [34]:
result_simple = df.groupby('year')[['PTS', 'REB']].mean()
print(result_simple)

            PTS       REB
year                     
2001   8.282324  3.762470
2002   9.531900  4.294624
2003   9.966854  4.539326
2004  10.263866  4.457983
2005   8.415691  3.656674
2006   8.510321  3.617431
2007   8.428146  3.635240
2008   8.567202  3.636468
2009   8.653118  3.683603
2010   8.389450  3.623853
2011  10.510460  4.494979
2012   8.293176  3.618588
2013   8.831084  3.779759
2014   8.483556  3.667333
2015   8.571047  3.704900
2016   8.642333  3.628294
2017   9.365000  3.809750
2018   9.447380  3.943450
2019  10.085926  4.149383
2020   9.888865  3.972489
2021   9.764026  3.958458
2022   9.846822  3.793856
2023  10.085517  3.911034


Étape 3 : Agrégation avancée avec plusieurs fonctions

In [38]:
# Définir les fonctions d’agrégation
aggregations = {
    'PTS': ['sum', 'mean', 'max'],  # total, moyenne, maximum
    'REB': ['sum', 'mean', 'std'],  # total, moyenne, écart-type
    'salary': ['sum', lambda x: x.quantile(0.9)]  # somme et 90ème percentile
}

# Appliquer groupby et agg
result_adv = df.groupby('year').agg(aggregations)
print(result_adv.head())

         PTS                      REB                          salary  \
         sum       mean   max     sum      mean       std         sum   
year                                                                    
2001  3420.6   8.282324  31.4  1553.9  3.762470  2.483855  1414961000   
2002  2659.4   9.531900  32.1  1198.2  4.294624  2.515321  1335412000   
2003  1774.1   9.966854  28.0   808.0  4.539326  2.621709  1045535000   
2004  1221.4  10.263866  30.7   530.5  4.457983  2.447638   819341000   
2005  3593.5   8.415691  35.4  1561.4  3.656674  2.404070  1718426001   

                  
      <lambda_0>  
year              
2001   8952000.0  
2002  11962400.0  
2003  13346700.0  
2004  14625000.0  
2005   9855000.0  


Étape 4 : Agrégation par équipe et par position

In [42]:
team_pos_agg = df.groupby(['team', 'POS']).agg({
    'PTS': ['mean', 'max'],
    'AST': 'mean',
    'REB': 'mean'
})
print(team_pos_agg.head(15))

                   PTS             AST       REB
                  mean   max      mean      mean
team    POS                                     
ATL     C     7.766667  18.6  1.060784  5.649020
        F     7.496429  14.8  1.075000  3.985714
        G     9.864103  25.0  2.758974  2.569231
        PF    9.585000  21.6  1.458333  5.076667
        PG   12.645161  29.6  4.864516  2.251613
        SF    9.232258  20.8  1.500000  3.496774
        SG    7.980000  22.5  1.902500  2.417500
ATL/BOS C     2.300000   2.3  0.400000  1.000000
        PF   19.100000  19.1  3.400000  9.000000
ATL/CHI PF    5.600000   5.6  0.600000  1.900000
        SF    4.500000   4.5  1.100000  1.700000
        SG    3.000000   3.0  1.600000  1.500000
ATL/CLE G    10.100000  10.1  1.600000  2.800000
        SG    5.200000   5.2  0.900000  2.200000
ATL/DAL C     3.500000   3.5  0.000000  4.000000


Étape 5 : Exploration des résultats

In [43]:
annee_max_pts = result_adv['PTS']['sum'].idxmax()
print(f"L'année avec le plus de points marqués est : {annee_max_pts}")

L'année avec le plus de points marqués est : 2022
