## 1. Primitives importantes de Numpy

1.1 Statisques de base

In [3]:
import numpy as np

data = np.array([1, 2, 3, 4])
mean_value = data.mean()
print("Moyenne :", mean_value)

Moyenne : 2.5


In [7]:
total = data.sum()
print("Somme :", total)

Somme : 10


In [9]:
variance = data.var()
print("Variance :", variance)

Variance : 1.25


1.2 Manipulation des tableaux

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6])
reshaped = data.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [13]:
data = np.array([[1,2],[3,4]])
print(data)
flattened = data.flatten()
print("===================\n",flattened)

[[1 2]
 [3 4]]
 [1 2 3 4]


In [14]:
transposed = data.transpose()
print(transposed)

[[1 3]
 [2 4]]


In [15]:
data1 = np.array([1,2])
data2 = np.array([3,4])
h_combined = np.hstack((data1, data2))
print("Horizontalement empilé :", h_combined)
v_combined = np.vstack((data1, data2))
print("Verticalement empilé :\n", v_combined)

Horizontalement empilé : [1 2 3 4]
Verticalement empilé :
 [[1 2]
 [3 4]]


In [ ]:
data = np.array([10, 20, 30, 40,])
last_element = data[-1]
print("Dernier élément :", last_element)

Dernier élément : 40


In [18]:
data = np.array([10, 20, 30, 40, 50])
slice_data = data[::2]
print("Éléments aux indices pairs :", slice_data)

Éléments aux indices pairs : [10 30 50]


In [21]:
data = np.array([1, 2, 3, 4])
copied_data = data.copy()
copied_data[0] = 99
print("Original :", data)
print("Copié :", copied_data)

Original : [1 2 3 4]
Copié : [99  2  3  4]


1.3 Affichage des primier et dernier élements du dataset

In [24]:
dataset = np.arange(1, 101)
print("Premiers éléments :", dataset[:10])
print("Derniers éléments :", dataset[-10:])

Premiers éléments : [ 1  2  3  4  5  6  7  8  9 10]
Derniers éléments : [ 91  92  93  94  95  96  97  98  99 100]


1.5 Indexation avancée

In [27]:
# Fancy Indexing
data = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
selected = data[indices]
print(selected)

[10 30 50]


In [29]:
# masking
data = np.array([1, 2, 3, 4, 5])
filtered = data[data > 3]
print(filtered)

[4 5]


In [34]:
# where()
data = np.array([10, 20, 30, 40, 50])
condition = data > 30
resutl = np.where(condition)
print(resutl)

(array([3, 4]),)


In [10]:
import numpy as np
import pandas as pd
data = np.array([
    {"Nom": "Alice", "Classe": "Guerrier", "Niveau": 5},
    {"Nom": "Bob",  "Classe": "Mage", "Niveau": 3},
    {"Nom": "Charlie", "Classe": "Guerrier", "Niveau": 7},
])
data = np.array([
    ("Alice", "Guerrier", 5),
    ("Bob", "Mage", 3),
    ("Charlie", "Guerrier", 7)
], dtype=[('Nom','S'), ('Classe','S'), ('Niveau','i4')])

# Sélectionner tout les guerriers
guerriers = data[data["Classe"] == "Guerrier"]
print(guerriers)

[]


In [13]:
import numpy as np
import pandas as pd
data = np.array([
    {"Nom": "Alice", "Classe": "Guerrier", "Niveau": 5},
    {"Nom": "Bob",  "Classe": "Mage", "Niveau": 3},
    {"Nom": "Charlie", "Classe": "Guerrier", "Niveau": 7},
])
data = pd.DataFrame(data.tolist())
# Sélectionner tout les guerriers
guerriers = data[data["Classe"] == "Guerrier"]
print(guerriers)

       Nom    Classe  Niveau
0    Alice  Guerrier       5
2  Charlie  Guerrier       7


In [17]:
import numpy as np

# Création des tableaux
A = np.array([1, 2, 3])        # Shape: (3,)
B = np.array([[1], [2], [3]])  # Shape: (3, 1)

print("Tableau A:")
print(f"Shape: {A.shape}")
print(f"Valeurs: {A}")
print("\nTableau B:")
print(f"Shape: {B.shape}")
print(f"Valeurs:\n{B}")

# Opération avec broadcasting
result = A + B
print("\nRésultat A + B:")
print(f"Shape: {result.shape}")
print(f"Valeurs:\n{result}")

Tableau A:
Shape: (3,)
Valeurs: [1 2 3]

Tableau B:
Shape: (3, 1)
Valeurs:
[[1]
 [2]
 [3]]

Résultat A + B:
Shape: (3, 3)
Valeurs:
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [21]:
df = pd.read_csv("C:/Users/David BOHORQUEZ/Downloads/archive/dataset_joueurs.csv")

df.head()

,pseudo,nb_parties,nb_victoires,team,class
0,Player_1,71,5,Green,Guerrier
1,Player_2,34,27,Red,Archer
2,Player_3,91,14,Blue,Archer
3,Player_4,80,72,Red,Healer
4,Player_5,40,19,Green,Archer
